### PR TITLE
updated the quaternion package

### PR DESCRIPTION
**Pull request by theNerd247**

### CODE REVIEW

**Comment by drizzd** [comment]
Thanks. I am looking for someone to share the effort of maintaining octave-forge AUR packages with:

https://lists.archlinux.org/pipermail/aur-general/2015-May/030531.html

Would you be interested, maybe?

**Comment by theNerd247** [comment]
Maybe. I don't use octave enough where I would be much use for this job. 
My recent involvement is mostly due to work.

Honestly it sounds like anyone with a decent background in crontab and
bash scripting could pull it off. I had an idea where a script could simply: 
1. poll their server (in some form or fashion - details will naturally follow an
   attempted implementation). 
2. run the ./newpkg on all of the packages (I assume if a package doesn't need
   to be updated then nothing happens. If not I may look into implementing this
   funcationality). 
3. push the changes to the server (poth github and AUR).

If an error occurs in the process the "maintainer" simply looks into the error
and fixes the problem before manually pushing the results.

In response to: https://lists.archlinux.org/pipermail/aur-general/2015-May/030531.html

I would say that my script idea above (which I gave before I read your link above) would be a great first attempt at automating this task. Might I suggest also looking into doing a single octave-forge package that just contains all of the packages in forge. They aren't large and you could include a list in the package build where the user can pick and choose which packages get installed. I would check with the demographics first (this may not be a well received/practical idea). 

PS: did you notice the out-of-date flag for linear-algebra and quaternion on the
AUR? That was my doing because I'm using those two packages for work.

**Comment by drizzd** [comment]
The packages you flagged are all updated.

It is possible to write PKGBUILDs which download the latest version from a git/svn repo etc. It should not be hard to do the same for upstream octave forge packages. They are ultimately shell scripts, so we just have to run newpkg inside the PKGBUILD.

If the latest version breaks, then it's an upstream bug which should be fixed there. So we only have maintenance effort if we want to do extra work and add workarounds to the PKGBUILDs.

Just like for linear-algebra where the latest version is broken because it depends on an Octave version which ist not released yet...

But maybe we should move the discussion to the archlinux forums. I wonder if anyone is following the aur-general mailing list for this kind of topic.

**Comment by drizzd** [comment]
I have played with this idea here:
https://github.com/drizzd/octave-forge-archlinux/commit/663ee4fd4b7671ad58a68b9fdd00f655de14d5bc

I think this could work, but notice the caveats in the commit message.

**Pull request merged**
